services:
    ByteSpin\MessengerDedupeBundle\Repository\MessengerMessageHashRepository:
        arguments:
            $registry: '@Doctrine\Persistence\ManagerRegistry'
    ByteSpin\MessengerDedupeBundle\EventSubscriber\MessageHashEventSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }
        arguments:
            $hashRepository: '@ByteSpin\MessengerDedupeBundle\Repository\MessengerMessageHashRepository'
            $entityManager: '@Doctrine\ORM\EntityManagerInterface'
    ByteSpin\MessengerDedupeBundle\Processor\HashProcessor:
        class: ByteSpin\MessengerDedupeBundle\Processor\HashProcessor
    ByteSpin\MessengerDedupeBundle\Middleware\DeduplicationMiddleware:
        class: ByteSpin\MessengerDedupeBundle\Middleware\DeduplicationMiddleware
        tags:
            - { name: 'messenger.middleware', bus: 'messenger.bus.default' }
        arguments:
            $hashRepository: '@ByteSpin\MessengerDedupeBundle\Repository\MessengerMessageHashRepository'
            $entityManager: '@Doctrine\ORM\EntityManagerInterface'
